/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr_management.GUI;

/**
 *
 * @author ishitajanwale
 */
public class CreateEmployeeProfile extends javax.swing.JPanel {

    /**
     * Creates new form CreateEmployeeProfile
     */
    public CreateEmployeeProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlblogin = new javax.swing.JLabel();
        EName = new javax.swing.JLabel();
        Eid = new javax.swing.JLabel();
        EAge = new javax.swing.JLabel();
        Egender = new javax.swing.JLabel();
        EStartDate = new javax.swing.JLabel();
        ELevel = new javax.swing.JLabel();
        Eposition = new javax.swing.JLabel();
        ETeam = new javax.swing.JLabel();
        Ecell = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        TEmpID = new javax.swing.JTextField();
        Tage = new javax.swing.JTextField();
        TGender = new javax.swing.JTextField();
        Tstartdate = new javax.swing.JTextField();
        Tlevel = new javax.swing.JTextField();
        TTeaminfo = new javax.swing.JTextField();
        Tposition = new javax.swing.JTextField();
        TCellNo = new javax.swing.JTextField();
        TEmail = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        Jlblogin.setBackground(new java.awt.Color(102, 102, 102));
        Jlblogin.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Jlblogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlblogin.setText("LOGIN");
        Jlblogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 162, 162), 3));

        EName.setBackground(new java.awt.Color(229, 210, 210));
        EName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        EName.setText("Name");
        EName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Eid.setBackground(new java.awt.Color(229, 210, 210));
        Eid.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Eid.setText("Employee ID");
        Eid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        EAge.setBackground(new java.awt.Color(229, 210, 210));
        EAge.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        EAge.setText("Age");
        EAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Egender.setBackground(new java.awt.Color(229, 210, 210));
        Egender.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Egender.setText("Gender");
        Egender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        EStartDate.setBackground(new java.awt.Color(229, 210, 210));
        EStartDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        EStartDate.setText("Start Date");
        EStartDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ELevel.setBackground(new java.awt.Color(229, 210, 210));
        ELevel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ELevel.setText("Level");
        ELevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Eposition.setBackground(new java.awt.Color(229, 210, 210));
        Eposition.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Eposition.setText("Position");
        Eposition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ETeam.setBackground(new java.awt.Color(229, 210, 210));
        ETeam.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ETeam.setText("Team info.");
        ETeam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Ecell.setBackground(new java.awt.Color(229, 210, 210));
        Ecell.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Ecell.setText("Cell no.");
        Ecell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Email.setBackground(new java.awt.Color(229, 210, 210));
        Email.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Email.setText("Email id.");
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Tname.setBackground(new java.awt.Color(229, 210, 210));
        Tname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Tname.setText(" ");
        Tname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TEmpID.setBackground(new java.awt.Color(229, 210, 210));
        TEmpID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        TEmpID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Tage.setBackground(new java.awt.Color(229, 210, 210));
        Tage.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Tage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TGender.setBackground(new java.awt.Color(229, 210, 210));
        TGender.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        TGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Tstartdate.setBackground(new java.awt.Color(229, 210, 210));
        Tstartdate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Tstartdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Tlevel.setBackground(new java.awt.Color(229, 210, 210));
        Tlevel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Tlevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TTeaminfo.setBackground(new java.awt.Color(229, 210, 210));
        TTeaminfo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        TTeaminfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Tposition.setBackground(new java.awt.Color(229, 210, 210));
        Tposition.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Tposition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TCellNo.setBackground(new java.awt.Color(229, 210, 210));
        TCellNo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        TCellNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TEmail.setBackground(new java.awt.Color(229, 210, 210));
        TEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        TEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jlblogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Ecell, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Eposition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ETeam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ELevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Egender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Eid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TGender, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TTeaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tposition, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCellNo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Jlblogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EName)
                    .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Eid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EAge)
                    .addComponent(Tage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Egender)
                    .addComponent(TGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EStartDate)
                    .addComponent(Tstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ELevel)
                    .addComponent(Tlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ETeam)
                    .addComponent(TTeaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eposition)
                    .addComponent(Tposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ecell)
                    .addComponent(TCellNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(TEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EAge;
    private javax.swing.JLabel ELevel;
    private javax.swing.JLabel EName;
    private javax.swing.JLabel EStartDate;
    private javax.swing.JLabel ETeam;
    private javax.swing.JLabel Ecell;
    private javax.swing.JLabel Egender;
    private javax.swing.JLabel Eid;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Eposition;
    private javax.swing.JLabel Jlblogin;
    private javax.swing.JTextField TCellNo;
    private javax.swing.JTextField TEmail;
    private javax.swing.JTextField TEmpID;
    private javax.swing.JTextField TGender;
    private javax.swing.JTextField TTeaminfo;
    private javax.swing.JTextField Tage;
    private javax.swing.JTextField Tlevel;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tposition;
    private javax.swing.JTextField Tstartdate;
    private javax.swing.JButton btnSubmit;
    // End of variables declaration//GEN-END:variables
}
