/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aed1;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ishitajanwale
 */
public class Form extends javax.swing.JFrame {

    DefaultTableModel model;
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        model= (DefaultTableModel) Etable.getModel();
    }
 String Gender=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Ename = new javax.swing.JLabel();
        Eid = new javax.swing.JLabel();
        Egender = new javax.swing.JLabel();
        Eage = new javax.swing.JLabel();
        Estartdate = new javax.swing.JLabel();
        Elevel = new javax.swing.JLabel();
        ETeam = new javax.swing.JLabel();
        ETitle = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Ecell = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        Tid = new javax.swing.JTextField();
        Tage = new javax.swing.JTextField();
        Tdate = new javax.swing.JTextField();
        Tlevel = new javax.swing.JTextField();
        Tinfo = new javax.swing.JTextField();
        Title = new javax.swing.JTextField();
        Tmail = new javax.swing.JTextField();
        Tcell = new javax.swing.JTextField();
        Rfemale = new javax.swing.JRadioButton();
        Rmale = new javax.swing.JRadioButton();
        Rother = new javax.swing.JRadioButton();
        ESearch = new javax.swing.JLabel();
        Tsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Etable = new javax.swing.JTable();
        ImageText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Image");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        Ename.setText("Name");

        Eid.setText("Employee ID");

        Egender.setText("Gender");

        Eage.setText("Age");

        Estartdate.setText("Start Date");

        Elevel.setText("Level");

        ETeam.setText("Team Information");

        ETitle.setText("Position Title");

        Email.setText("Email");

        Ecell.setText("Cell number");

        Rfemale.setText("Female");
        Rfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RfemaleActionPerformed(evt);
            }
        });

        Rmale.setText("Male");

        Rother.setText("Other");

        ESearch.setText("Search");
        ESearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Etable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        Etable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EtableMouseClicked(evt);
            }
        });
        Etable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EtableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Etable);

        ImageText.setText("Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(ESearch)
                .addGap(87, 87, 87)
                .addComponent(Tsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImageText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Eid)
                            .addComponent(Ename)
                            .addComponent(Egender)
                            .addComponent(Eage)
                            .addComponent(Estartdate)
                            .addComponent(ETitle)
                            .addComponent(Ecell)
                            .addComponent(Email)
                            .addComponent(ETeam)
                            .addComponent(Elevel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Rmale)
                                .addGap(18, 18, 18)
                                .addComponent(Rfemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Rother))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Tdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(Tage, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Tname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(Tid, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Tmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(Tcell, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tlevel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tinfo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Title, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(633, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ename)
                            .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eid)
                            .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Egender)
                            .addComponent(Rfemale)
                            .addComponent(Rmale)
                            .addComponent(Rother))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eage)
                            .addComponent(Tage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Estartdate)
                            .addComponent(Tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ETitle)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ETeam)
                            .addComponent(Tinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Elevel)
                            .addComponent(Tlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ecell)
                            .addComponent(Tcell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email)
                            .addComponent(Tmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ESearch)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImageText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(Rmale.isSelected()==true){
            Gender ="Male";
        }
        else if (Rfemale.isSelected()==true){
            Gender ="Female";
        }
        else{
            Gender="Other";
        }
        
        if(Tname.getText().equals(" ") || Tid.getText().equals(" ") || Tage.getText().equals(" ") || Gender.equals(" ") || Title.getText().equals(" ")|| Tlevel.getText().equals(" ")|| Tinfo.getText().equals(" ")|| Tdate.getText().equals(" ")|| Tcell.getText().equals(" ")|| Tmail.getText().equals(" "))
        {
            JOptionPane.showMessageDialog(this, " Add the complete data");
        }
        else
        {
            String data[]={Tname.getText(),Tid.getText(),Tage.getText(),/*Gender*/Tid.getText(),Tlevel.getText(),Tinfo.getText(),Tlevel.getText(),Tcell.getText(),Tmail.getText(),
            };
            DefaultTableModel Model=(DefaultTableModel)Etable.getModel();
            Model.addRow(data);
            JOptionPane.showMessageDialog(this, " Data Addedd Sucessfully");
            
           Tname.setText(" ");
            
            Tid.setText(" ");
            
            Tage.setText(" ");
            
                    
            Gender = " ";
            //buttonGroup1.clearSelection();
            
          //  Gender.setText(" ");
            Tlevel.setText(" ");
            Tinfo.setText(" ");
            Title.setText(" ");
            Tcell.setText(" ");
            Tmail.setText(" ");
           
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        {
        int i = Etable.getSelectedRow();
        if (i>=0){
            model.removeRow(i);
            JOptionPane.showMessageDialog(this, "Removed Data Successfully");
        }
        else{
            JOptionPane.showMessageDialog(this, "Select a Row");
        }
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RfemaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int i = Etable.getSelectedRow();
        
        
        if(i>=0)
        {
            if(Rmale.isSelected()==true)
            {
            Gender ="Male";
            }
            else if (Rfemale.isSelected()==true)
            {
            Gender ="Female";
            }
            else
            {
            Gender="Other";
            }
           
            model.setValueAt(Tname.getText(), i, 0);
            model.setValueAt(Tid.getText(), i, 1);
            model.setValueAt(Tage.getText(), i, 2);
            model.setValueAt(Gender, i, 3);
            JOptionPane.showMessageDialog(this, "Updated!");
            Tname.setText("");
            Tid.setText("");
            Tage.setText("");
            Gender = "";  
            //buttonGroup1.clearSelection();
            }
        else{
            JOptionPane.showMessageDialog(this,"Please Select a Row!");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EtableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EtableKeyReleased
        // TODO add your handling code here:

        DefaultTableModel table = (DefaultTableModel)Etable.getModel();
        String search = ESearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        Etable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_EtableKeyReleased

    private void EtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtableMouseClicked
        // TODO add your handling code here:

        int i=Etable.getSelectedRow();

        Tname.setText(model.getValueAt(i, 0).toString());
        Tid.setText(model.getValueAt(i, 1).toString());
        Tage.setText(model.getValueAt(i, 2).toString());
        if("Male".equals(model.getValueAt(i, 3))){
            Rmale.setSelected(true);
        }
        else if("Female".equals(model.getValueAt(i, 3))){
            Rfemale.setSelected(true);
        } else{
            Rother.setSelected(true);
        }

        Tdate.setText(model.getValueAt(i, 3).toString());
        Tlevel.setText(model.getValueAt(i, 5).toString());
        Title.setText(model.getValueAt(i, 6).toString());
        Tinfo.setText(model.getValueAt(i, 7).toString());
        Tcell.setText(model.getValueAt(i, 8).toString());
        Tmail.setText(model.getValueAt(i, 9).toString());
    }//GEN-LAST:event_EtableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:JFileChooser browseImageFile = new JFileChooser();
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
   
        
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
        File selectedImageFile = browseImageFile.getSelectedFile();
        String selectedImagePath = selectedImageFile.getAbsolutePath();
        JOptionPane.showMessageDialog(null, selectedImagePath);
        
     ImageIcon ii = new ImageIcon(selectedImagePath);
     Image image = ii.getImage().getScaledInstance(ImageText.getWidth(),ImageText.getHeight(),Image.SCALE_SMOOTH);
        
      ImageText.setIcon(new ImageIcon(image));
    }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ESearch;
    private javax.swing.JLabel ETeam;
    private javax.swing.JLabel ETitle;
    private javax.swing.JLabel Eage;
    private javax.swing.JLabel Ecell;
    private javax.swing.JLabel Egender;
    private javax.swing.JLabel Eid;
    private javax.swing.JLabel Elevel;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Ename;
    private javax.swing.JLabel Estartdate;
    private javax.swing.JTable Etable;
    private javax.swing.JLabel ImageText;
    private javax.swing.JRadioButton Rfemale;
    private javax.swing.JRadioButton Rmale;
    private javax.swing.JRadioButton Rother;
    private javax.swing.JTextField Tage;
    private javax.swing.JTextField Tcell;
    private javax.swing.JTextField Tdate;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tinfo;
    private javax.swing.JTextField Title;
    private javax.swing.JTextField Tlevel;
    private javax.swing.JTextField Tmail;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tsearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
